### ISSUE TITLE
Breast Cancer Prediction

### ISSUE THREAD

**Issue by aindree-2005** [Yashpatel191001/Amazing-Python-Scripts#12]
I would like to a Python script for detecting Breast Cancer using KNN. It's a pretty beginner friendly topic and I believe that it can be really in sync with the goals of this repo. 
@Yashpatel191001 It would be great if this task could be assigned to me!

**Comment by Yashpatel191001** [comment]
Go ahead @aindree-2005

**Comment by Yashpatel191001** [comment]
Yes @Ayush-865 , Your PRs will be merged and will be consider for Hacktoberfest 2023.

**Comment by aindree-2005** [comment]
@Yashpatel191001 I have added a folder containing the notebook and code for breast cancer prediction and created a pull request
