### ISSUE TITLE
MEDV(Median value of owner-occupied homes) dataset

### ISSUE THREAD

**Issue by EngineerAnishSharma** [Yashpatel191001/Amazing-Python-Scripts#47]
@Yashpatel191001 pls add hacktoberfest tag

**Comment by Yashpatel191001** [comment]
@EngineerAnishSharma What's MEDV? Please provide proper details.

**Comment by EngineerAnishSharma** [comment]
The MEDV (Median value of owner-occupied homes) dataset is a well-known dataset in the field of machine learning and statistics. It is often used for regression analysis and predictive modeling. This dataset is typically used to explore the relationship between various features or attributes of a house and its corresponding median value.

**Comment by Yashpatel191001** [comment]
Go ahead @EngineerAnishSharma
