### ISSUE TITLE
FIFA 20 Dataset Analysis

### ISSUE THREAD

**Issue by EngineerAnishSharma** [Yashpatel191001/Amazing-Python-Scripts#49]
@Yashpatel191001 pls add hacktoberfest tag

**Comment by Yashpatel191001** [comment]
@EngineerAnishSharma EDA on which Dataset? Mentioned everything properly.

**Comment by EngineerAnishSharma** [comment]
> @EngineerAnishSharma EDA on which Dataset? Mentioned everything properly.

FIFA 20 Dataset Analysis
This script performs a basic analysis of the FIFA 20 dataset using the Pandas library in Python. It explores various aspects of the dataset, such as player nationalities, player salaries, and player attributes. The script utilizes data visualization techniques using Matplotlib and Seaborn to present the findings in graphical form.

**Comment by EngineerAnishSharma** [comment]
I have mentioned everything pls check. Thank you

**Comment by Yashpatel191001** [comment]
Go ahead @EngineerAnishSharma
