### ISSUE TITLE
#feature : Add a machine learning model to translate sign language to text for deaf and mute people

### ISSUE THREAD

**Issue by Ayush-865** [Yashpatel191001/Amazing-Python-Scripts#6]

**Comment by Ayush-865** [comment]
Please add hacktoberfest  and hacktoberfest accepted label to my issue and accept my pr

**Comment by Yashpatel191001** [comment]
Go ahead @Ayush-865

**Comment by Ayush-865** [comment]
@Yashpatel191001 are your codes getting accepted for hacktoberfest??
